"""Application service models for current portfolio income analysis."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import timedelta
from decimal import Decimal
from pathlib import Path

from src.controlled_positions_import import ControlledPositionsImportService
from src.current_income import CurrentIncome, CurrentIncomeResult
from src.import_operation_store import ImportOperationStore
from src.income_portfolio import IncomePortfolio
from src.portfolio import Portfolio
from src.snapshot_store import SnapshotStore
from src.transaction import InvestmentTransaction
from src.transaction_repository import TransactionRepository


@dataclass(frozen=True, slots=True)
class IncomeHoldingAnalysis:
    """Recurring income analysis for one current portfolio holding."""

    symbol: str
    market_value: Decimal
    portfolio_weight: Decimal
    cost_basis: Decimal
    all_history_recurring_income: Decimal
    trailing_12_month_recurring_income: Decimal
    income_weight: Decimal
    unrealized_gain_loss: Decimal
    unrealized_gain_loss_percent: Decimal
    trailing_12_month_yield: Decimal
    yield_on_cost: Decimal

@dataclass(frozen=True, slots=True)
class IncomeAnalysisResult:
    """Summary of recurring income generated by current holdings."""

    holdings: tuple[IncomeHoldingAnalysis, ...]
    market_value: Decimal
    all_history_recurring_income: Decimal
    trailing_12_month_recurring_income: Decimal
    trailing_12_month_income_yield: Decimal
    all_history_income_from_no_longer_held: Decimal
    all_history_symbolless_income: Decimal
    holdings_with_income: int
    holdings_without_income: int
    largest_income_holding_symbol: str | None
    largest_income_holding_amount: Decimal
    largest_income_holding_weight: Decimal
    top_five_income_weight: Decimal

class IncomeAnalysisService:
    """Application service for current portfolio income analysis."""

    def __init__(
        self,
        import_operation_store: ImportOperationStore,
        snapshot_store: SnapshotStore,
        transaction_repository: TransactionRepository,
    ) -> None:
        self._import_operation_store = import_operation_store
        self._snapshot_store = snapshot_store
        self._transaction_repository = transaction_repository
        self._positions_import_service = ControlledPositionsImportService(
            import_operation_store=import_operation_store,
            snapshot_store=snapshot_store,
        )

    def load_current_portfolio(self) -> Portfolio | None:
        """Load the authoritative current portfolio."""
        snapshot = self._positions_import_service.load_current_portfolio()

        if snapshot is None:
            return None

        return Portfolio(
            name=snapshot.portfolio_name,
            holdings=list(snapshot.holdings),
        )

    def analyze_current_income(
        self,
        portfolio: Portfolio,
        transactions: list[InvestmentTransaction],
    ) -> CurrentIncomeResult:
        """Analyze historical income generated by current holdings."""
        return CurrentIncome(
            portfolio=portfolio,
            transactions=transactions,
        ).analyze()

    def trailing_12_month_transactions(
        self,
        transactions: list[InvestmentTransaction],
    ) -> tuple[InvestmentTransaction, ...]:
        """Return recurring income transactions from the trailing 12 months."""
        if not transactions:
            return ()

        end_date = max(
            transaction.transaction_date for transaction in transactions
        )
        start_date = end_date - timedelta(days=365)

        return tuple(
            transaction
            for transaction in transactions
            if (
                transaction.is_recurring_income
                and start_date <= transaction.transaction_date <= end_date
            )
        )

    def analyze_trailing_12_month_income(
        self,
        portfolio: Portfolio,
        transactions: list[InvestmentTransaction],
    ) -> CurrentIncomeResult:
        """Analyze recurring income during the trailing 12 months."""
        ttm_transactions = self.trailing_12_month_transactions(transactions)

        return CurrentIncome(
            portfolio=portfolio,
            transactions=ttm_transactions,
        ).analyze()

    def build_holding_analysis(
        self,
        portfolio: Portfolio,
        all_history_income: CurrentIncomeResult,
        ttm_income: CurrentIncomeResult,
    ) -> tuple[IncomeHoldingAnalysis, ...]:
        """Build income analysis for each current portfolio holding."""
        total_market_value = portfolio.total_market_value
        total_ttm_income = ttm_income.total_recurring_income

        all_history_by_symbol = {
            holding.symbol: holding.recurring_historical_income
            for holding in all_history_income.holding_income
        }
        ttm_by_symbol = {
            holding.symbol: holding.recurring_historical_income
            for holding in ttm_income.holding_income
        }

        results = []

        for holding in portfolio.holdings:
            if holding.market_value == 0:
                continue

            market_value = holding.market_value
            cost_basis = holding.cost_basis
            ttm_income_amount = ttm_by_symbol.get(
                holding.symbol,
                Decimal("0"),
            )
            all_history_income_amount = all_history_by_symbol.get(
                holding.symbol,
                Decimal("0"),
            )

            portfolio_weight = (
                (market_value / total_market_value) * Decimal("100")
                if total_market_value
                else Decimal("0")
            )
            income_weight = (
                (ttm_income_amount / total_ttm_income) * Decimal("100")
                if total_ttm_income
                else Decimal("0")
            )
            unrealized_gain_loss = market_value - cost_basis

            unrealized_gain_loss_percent = (
                (
                    (market_value / cost_basis)
                    - Decimal("1")
                )
                * Decimal("100")
                if cost_basis
                else Decimal("0")
            )
            trailing_12_month_yield = (
                (ttm_income_amount / market_value) * Decimal("100")
                if market_value
                else Decimal("0")
            )
            yield_on_cost = (
                (ttm_income_amount / cost_basis) * Decimal("100")
                if cost_basis
                else Decimal("0")
            )

            results.append(
                IncomeHoldingAnalysis(
                    symbol=holding.symbol,
                    market_value=market_value,
                    portfolio_weight=portfolio_weight,
                    cost_basis=cost_basis,
                    all_history_recurring_income=all_history_income_amount,
                    trailing_12_month_recurring_income=ttm_income_amount,
                    income_weight=income_weight,
                    unrealized_gain_loss=unrealized_gain_loss,
                    unrealized_gain_loss_percent=(
                        unrealized_gain_loss_percent
                    ),
                    trailing_12_month_yield=trailing_12_month_yield,
                    yield_on_cost=yield_on_cost,
                )
            )

        return tuple(results)

    def analyze(self) -> IncomeAnalysisResult | None:
        """Build the complete current portfolio income analysis."""
        portfolio = self.load_current_portfolio()

        if portfolio is None:
            return None

        transactions = self._transaction_repository.all_transactions()

        all_income_portfolio = IncomePortfolio(
            portfolio,
            transactions,
        ).reconcile()

        all_history_income = self.analyze_current_income(
            portfolio,
            transactions,
        )
        ttm_income = self.analyze_trailing_12_month_income(
            portfolio,
            transactions,
        )
        holdings = self.build_holding_analysis(
            portfolio,
            all_history_income,
            ttm_income,
        )
        income_ranked_holdings = sorted(
            holdings,
            key=lambda holding: holding.trailing_12_month_recurring_income,
            reverse=True,
        )
        largest_income_holding = (
            income_ranked_holdings[0]
            if income_ranked_holdings
            else None
        )
        top_five_income_weight = sum(
            (
                holding.income_weight
                for holding in income_ranked_holdings[:5]
            ),
            Decimal("0"),
        )

        return IncomeAnalysisResult(
            holdings=holdings,
            market_value=portfolio.total_market_value,
            all_history_recurring_income=(
                all_history_income.total_recurring_income
            ),
            trailing_12_month_recurring_income=(
                ttm_income.total_recurring_income
            ),
            trailing_12_month_income_yield=(
                (
                    ttm_income.total_recurring_income
                    / portfolio.total_market_value
                )
                * Decimal("100")
                if portfolio.total_market_value
                else Decimal("0")
            ),
            all_history_income_from_no_longer_held=(
                all_income_portfolio.total_historical_income_from_no_longer_held
            ),
            all_history_symbolless_income=(
                all_income_portfolio.total_symbolless_historical_income
            ),
            holdings_with_income=len(
                all_history_income.holdings_with_income
            ),
            holdings_without_income=len(
                all_history_income.holdings_without_income
            ),
            largest_income_holding_symbol=(
                largest_income_holding.symbol
                if largest_income_holding is not None
                else None
            ),
            largest_income_holding_amount=(
                largest_income_holding.trailing_12_month_recurring_income
                if largest_income_holding is not None
                else Decimal("0")
            ),
            largest_income_holding_weight=(
                largest_income_holding.income_weight
                if largest_income_holding is not None
                else Decimal("0")
            ),
            top_five_income_weight=top_five_income_weight,
        )

def create_income_analysis_service(
    import_operation_path: str | Path,
    snapshot_path: str | Path,
    transaction_path: str | Path,
) -> IncomeAnalysisService:
    """Create an IncomeAnalysisService using RIMS persistence locations."""
    import_operation_store = ImportOperationStore(
        Path(import_operation_path),
    )
    snapshot_store = SnapshotStore(
        Path(snapshot_path),
    )
    transaction_repository = TransactionRepository.from_path(
        Path(transaction_path),
    )

    return IncomeAnalysisService(
        import_operation_store=import_operation_store,
        snapshot_store=snapshot_store,
        transaction_repository=transaction_repository,
    )
