"""Current portfolio income analysis.

Sprint 19J provides the analysis layer that connects the current portfolio
with its historical income experience.

This module reports actual historical income from securities that are
currently held. It does not annualize, project, or substitute current yield
for historical income.
"""

from dataclasses import dataclass
from decimal import Decimal
from typing import TYPE_CHECKING

from .income_portfolio import IncomePortfolio
from .transaction import InvestmentTransaction

if TYPE_CHECKING:
    from .portfolio import Portfolio


@dataclass(frozen=True, slots=True)
class CurrentHoldingIncome:
    """Historical income information for one currently held security."""

    symbol: str
    shares: Decimal
    market_value: Decimal
    historical_income: Decimal
    recurring_historical_income: Decimal
    percentage_of_recurring_income: Decimal
    has_historical_income: bool


@dataclass(frozen=True, slots=True)
class CurrentIncomeResult:
    """Portfolio-level current income analysis result."""

    holding_income: tuple[CurrentHoldingIncome, ...]
    total_market_value: Decimal
    total_historical_income: Decimal
    total_recurring_income: Decimal
    holdings_with_income: tuple[str, ...]
    holdings_without_income: tuple[str, ...]
    income_concentration: Decimal
    symbolless_historical_income: Decimal


class CurrentIncome:
    """Analyze historical income generated by the current portfolio."""

    def __init__(
        self,
        portfolio: "Portfolio",
        transactions: tuple[InvestmentTransaction, ...],
    ) -> None:
        """Initialize current income analysis.

        Args:
            portfolio: Current RIMS portfolio.
            transactions: Historical investment transactions.

        Raises:
            TypeError: If portfolio or transactions have invalid types.
        """
        from .portfolio import Portfolio

        if not isinstance(portfolio, Portfolio):
            raise TypeError("portfolio must be a Portfolio")

        if not isinstance(transactions, tuple):
            raise TypeError("transactions must be a tuple")

        if not all(
            isinstance(transaction, InvestmentTransaction)
            for transaction in transactions
        ):
            raise TypeError(
                "transactions must contain only InvestmentTransaction objects"
            )

        self._portfolio = portfolio
        self._transactions = transactions

    def analyze(self) -> CurrentIncomeResult:
        """Produce current portfolio historical income analysis."""
        reconciliation = IncomePortfolio(
            self._portfolio,
            self._transactions,
        ).reconcile()

        current_holdings = self._current_holdings()

        total_market_value = sum(
            (holding.market_value for holding in current_holdings),
            Decimal("0"),
        )

        total_historical_income = (
            reconciliation.total_historical_income_from_current_holdings
        )
        total_recurring_income = (
            reconciliation.total_recurring_income_from_current_holdings
        )

        holding_income: list[CurrentHoldingIncome] = []

        for holding in current_holdings:
            historical_income = reconciliation.historical_income_by_current_holding.get(
                holding.symbol,
                Decimal("0"),
            )
            recurring_income = reconciliation.recurring_income_by_current_holding.get(
                holding.symbol,
                Decimal("0"),
            )

            if total_recurring_income > Decimal("0"):
                percentage = (
                    recurring_income / total_recurring_income
                ) * Decimal("100")
            else:
                percentage = Decimal("0")

            holding_income.append(
                CurrentHoldingIncome(
                    symbol=holding.symbol,
                    shares=holding.shares,
                    market_value=holding.market_value,
                    historical_income=historical_income,
                    recurring_historical_income=recurring_income,
                    percentage_of_recurring_income=percentage,
                    has_historical_income=historical_income != Decimal("0"),
                )
            )

        holdings_with_income = tuple(
            item.symbol
            for item in holding_income
            if item.has_historical_income
        )

        holdings_without_income = tuple(
            item.symbol
            for item in holding_income
            if not item.has_historical_income
        )

        income_concentration = self._income_concentration(
            holding_income,
            total_recurring_income,
        )

        return CurrentIncomeResult(
            holding_income=tuple(holding_income),
            total_market_value=total_market_value,
            total_historical_income=total_historical_income,
            total_recurring_income=total_recurring_income,
            holdings_with_income=holdings_with_income,
            holdings_without_income=holdings_without_income,
            income_concentration=income_concentration,
            symbolless_historical_income=(
                reconciliation.total_symbolless_historical_income
            ),
        )

    def _current_holdings(self) -> tuple["Holding", ...]:
        """Return current holdings with positive shares."""
        return tuple(
            holding
            for holding in self._portfolio.holdings
            if holding.shares > Decimal("0")
        )

    @staticmethod
    def _income_concentration(
        holding_income: list[CurrentHoldingIncome],
        total_recurring_income: Decimal,
    ) -> Decimal:
        """Return the percentage of recurring income from the largest holding."""
        if total_recurring_income <= Decimal("0"):
            return Decimal("0")

        largest_income = max(
            (
                item.recurring_historical_income
                for item in holding_income
            ),
            default=Decimal("0"),
        )

        return (
            largest_income / total_recurring_income
        ) * Decimal("100")


def analyze_current_income(
    portfolio: "Portfolio",
    transactions: tuple[InvestmentTransaction, ...],
) -> CurrentIncomeResult:
    """Convenience function for current portfolio income analysis."""
    return CurrentIncome(portfolio, transactions).analyze()